function originFromRequestHeaders(req: Request): string | null {
  const host = (req.headers.get("x-forwarded-host") ?? req.headers.get("host") ?? "").split(",")[0]?.trim();
  if (!host) return null;
  const proto =
    req.headers.get("x-forwarded-proto") ??
    (host.startsWith("localhost") || host.startsWith("127.") ? "http" : "https");
  return `${proto}://${host}`;
}

/**
 * Canonical public origin (emails, server routes without a Request).
 * Prefer NEXT_PUBLIC_APP_URL, then Vercel deployment host, then localhost.
 */
export function getPublicAppOrigin(): string {
  const configured = process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "").trim();
  if (configured) return configured;

  const vercelHost = process.env.VERCEL_URL?.replace(/^https?:\/\//, "").trim();
  if (vercelHost) return `https://${vercelHost}`;

  return "http://localhost:3000";
}

/**
 * Origin for links generated by an API route (detect-changes, send-report).
 * Prefer the host that served the request so preview deployments do not emit
 * production URLs (and vice versa) when NEXT_PUBLIC_APP_URL is set globally.
 */
export function getPublicOriginFromRequest(req: Request): string {
  return originFromRequestHeaders(req) ?? getPublicAppOrigin();
}
